from contextlib import contextmanager
from datetime import datetime
from typing import Generator, Optional

from sqlalchemy import inspect, text
from sqlmodel import Field, Session, SQLModel, create_engine

from config import DB_PATH


class PortfolioState(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    cash: float
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class Position(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    ticker: str = Field(index=True, unique=True)
    qty: float
    avg_cost: float
    realized_pnl: float = 0.0


class Trade(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    order_id: str = Field(index=True)
    ticker: str = Field(index=True)
    side: str = Field(index=True)
    qty: float
    fill_price: float
    fee: float = 0.0
    note: Optional[str] = None
    skill_used: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow, index=True)


class Signal(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    ticker: str = Field(index=True)
    signal: str = Field(index=True)
    confidence: float
    reason: str
    skill_used: str = "openclaw"
    price_at_signal: Optional[float] = None
    screen_scope: Optional[str] = None
    screen_label: Optional[str] = None
    universe: Optional[str] = None
    watchlist_member: bool = False
    acted_on: bool = False
    timestamp: datetime = Field(default_factory=datetime.utcnow, index=True)


class BenchmarkSnapshot(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    date: str = Field(index=True, unique=True)
    spy_price: float
    portfolio_value: float
    cash: float
    equity: float
    created_at: datetime = Field(default_factory=datetime.utcnow)

# ─────────────────────────────────────────────────────────────
# Autonomous Trading Pipeline
# ─────────────────────────────────────────────────────────────

class ResearchBrief(SQLModel, table=True):
    """
    One row per weekly research run (Monday morning).
    Stores the structured output from the Claude research agent.
    """
    id:             Optional[int]  = Field(default=None, primary_key=True)
    week_of:        str            = Field(index=True)          # "YYYY-MM-DD" (Monday)
    strategy:       str            = ""                          # momentum | mean_reversion | ...
    time_horizon:   str            = ""                          # e.g. "3-5 day swing"
    risk_posture:   str            = "moderate"                  # aggressive | moderate | conservative
    themes:         str            = "[]"                        # JSON list
    focus_sectors:  str            = "[]"                        # JSON list
    avoid_sectors:  str            = "[]"                        # JSON list
    watchlist_add:  str            = "[]"                        # JSON list of tickers added
    watchlist_remove: str          = "[]"                        # JSON list of tickers removed
    earnings_watch: str            = "[]"                        # JSON list of tickers with catalysts
    macro_summary:  str            = ""
    key_risks:      str            = ""
    rationale:      str            = ""
    raw_json:       Optional[str]  = None                        # full JSON from Claude
    created_at:     datetime       = Field(default_factory=datetime.utcnow, index=True)
 
 
class BlogPost(SQLModel, table=True):
    """
    One row per weekly blog post (Sunday evening).
    Content is raw markdown generated by the Claude blog agent.
    """
    id:             Optional[int]  = Field(default=None, primary_key=True)
    week_of:        str            = Field(index=True)           # "YYYY-MM-DD" (Monday of that week)
    iso_week:       str            = Field(index=True)           # "YYYY-WNN"
    title:          str            = ""
    summary:        str            = ""                          # executive summary paragraph
    content:        str            = ""                          # full markdown
    week_pnl:       float          = 0.0                         # realized P&L for the week
    spy_return_pct: Optional[float]= None                        # SPY weekly return %
    trades_count:   int            = 0
    strategy:       str            = ""                          # strategy from research brief
    created_at:     datetime       = Field(default_factory=datetime.utcnow, index=True)


engine = create_engine(
    f"sqlite:///{DB_PATH}",
    connect_args={"check_same_thread": False},
)

# ─────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────

def _ensure_signal_columns() -> None:
    inspector = inspect(engine)
    tables = set(inspector.get_table_names())
    if "signal" not in tables:
        return

    existing = {column["name"] for column in inspector.get_columns("signal")}
    migrations = {
        "screen_scope": "ALTER TABLE signal ADD COLUMN screen_scope VARCHAR",
        "screen_label": "ALTER TABLE signal ADD COLUMN screen_label VARCHAR",
        "universe": "ALTER TABLE signal ADD COLUMN universe VARCHAR",
        "watchlist_member": "ALTER TABLE signal ADD COLUMN watchlist_member BOOLEAN DEFAULT 0",
    }

    with engine.begin() as conn:
        for column, ddl in migrations.items():
            if column not in existing:
                conn.execute(text(ddl))

def _ensure_pipeline_columns() -> None:
    """
    Migration-safe column additions for ResearchBrief and BlogPost.
    Mirrors the pattern of _ensure_signal_columns().
    Run after SQLModel.metadata.create_all() so the tables exist.
    """
    from sqlalchemy import inspect, text
 
    inspector = inspect(engine)
    existing_tables = set(inspector.get_table_names())
 
    migrations: dict[str, dict[str, str]] = {
        "researchbrief": {
            "earnings_watch": "ALTER TABLE researchbrief ADD COLUMN earnings_watch VARCHAR DEFAULT '[]'",
            "raw_json":       "ALTER TABLE researchbrief ADD COLUMN raw_json VARCHAR",
        },
        "blogpost": {
            "spy_return_pct": "ALTER TABLE blogpost ADD COLUMN spy_return_pct FLOAT",
            "iso_week":       "ALTER TABLE blogpost ADD COLUMN iso_week VARCHAR",
        },
    }
 
    with engine.begin() as conn:
        for table, columns in migrations.items():
            if table not in existing_tables:
                continue
            existing_cols = {c["name"] for c in inspector.get_columns(table)}
            for col_name, ddl in columns.items():
                if col_name not in existing_cols:
                    conn.execute(text(ddl))


def init_db() -> None:
    SQLModel.metadata.create_all(engine)
    _ensure_signal_columns()
    _ensure_pipeline_columns()


def get_session() -> Generator[Session, None, None]:
    with Session(engine) as session:
        yield session


@contextmanager
def session_scope() -> Generator[Session, None, None]:
    with Session(engine) as session:
        yield session
